apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: default
type: Opaque
stringData:
  STRIPE_SECRET: "sk_test_51LtBf9FsFJxYdlw1nNBjlrHWFXErIt1O2vEWCQL2V4aN8nHnFwy0njrf14yAHyqn4vUCegQZk4UXg1zNMif5SOuN00SLJatgJO"
